### ISSUE TITLE
this woud be correct

### ISSUE THREAD

**Issue by Rudra-Kumar-Dubey** [Waqar-107/LeetCode#2]
class Solution
{
public:
ListNode* addTwoNumbers(ListNode* l1, ListNode* l2)
{
// Create Head Node that will be returned in the end
ListNode* head = new ListNode();
// Create Node that always will be current
ListNode* current = head;

**Comment by Waqar-107** [comment]
1. Which problem?
2. Is there something wrong with my code? if it is a bug in my solution then can you please mention it?
3. You haven't provided the whole code. 
4. If there's no bug or any indentation issue or any bad coding practice adopted in the code then I would like to close the issue 😃.

Also, you can use Labels while opening issues on Github that would give more insights to the repository maintainer. Happy Coding!!
